kind = "web"
previewPath = "/"
title = "KARAN.EXE"
version = "1.0.0"
id = "artifacts/karan"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24606

[services.development]
run = "pnpm --filter @workspace/karan run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/karan", "run", "build" ]
publicDir = "artifacts/karan/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24606"
BASE_PATH = "/"
