uploads = []
generated = []

[[outputs]]
id = "_jJSorlE6a6zi84Ue9zNu"
uri = "file://exports/wind-breaker-project.tar.gz"
type = "unspecified"
title = "Wind Breaker — Full Project Export"

[[outputs]]
id = "_4PjYXMu8oTIO_I-F-7IX"
uri = "file://wind-breaker.tar.gz"
type = "unspecified"
title = "wind-breaker.tar.gz — Full source code"
